### PR TITLE
Add ignoreNetFrameworkProjects for .net core task

### PR DESCRIPTION
**Pull request by hermanvos**
When specified this disables the warning in the logs for .NET framework projects.

### CODE REVIEW

**Comment by hermanvos** [comment]
This is a potential solution for #136 

I don't know how to test this change, but if you give guidance then I'm more than happy to test it. The change looks to be pretty low risk. I've left it an optional param that defaults to how the behavior was prior to this parameter being added.

**Comment by BMuuN** [comment]
Thanks for the contribution @hermanvos 🤘

**Comment by hermanvos** [comment]
Thanks for merging @BMuuN and happy to help.

When do you think this enhancement will be available on the azure devops store?

**Comment by BMuuN** [comment]
I'll configure a test build for the change and if all is good I'll push it tomorrow 👍

**Pull request merged**
