### PR TITLE
Issue #116 - Adding support for .props files

### PR DESCRIPTION
**Pull request by godefroyo**

### CODE REVIEW

**Comment by BMuuN** [comment]
@godefroyo thanks for the PR!  Any chance you can add a test project or file to the `tests` directory so I can add it to the build pipeline?

**Comment by godefroyo** [comment]
Sorry for taking that long, totally forgot 😢
I added an example of .props file (after getting rid of my editors problems, morning is way too difficult 😄)
Did no see a lot more to do. Tell me if you see something wrong

**Comment by BMuuN** [comment]
No worries at all I appreciate you taking the time to contribute!

Forgive my ignorance as I've not worked with custom build property files before but;
- could a `.props` file contain multiple `<PropertyGroup>` elements?
- would a `.props` file contain a `<TargetFramework>` or `<TargetFrameworks>` element?

The reason I ask; there's check in the code to ensure the assembly tags are added only once and are added to the correct `<PropertyGroup>`.  I do this by checking for a `<TargetFramework>` or `<TargetFrameworks>` element:

image

Without this check assembly tags would get added for every `<PropertyGroup>` found within a file.  As your example `Directory.Build.props` file doesn't contain either `<TargetFramework>` or `<TargetFrameworks>` element the code is exiting at the loop in the above screenshot.

So; I'm wondering how best to handle `*.props` files at this stage.  Can we add a  `<TargetFramework>` or `<TargetFrameworks>` element to the `Directory.Build.props` file?  Is this valid and would it be valid for both Net Core/Standard and Net Framework build projects? (again, apologies for my ignorance as I've not worked with custom build property files before).

**Comment by IanMercer** [comment]
shared.props files can (and do in my case) contain more than one `<PropertyGroup>`. The logic shown above might not work for all csproj files as we may have moved these values to a separate `<PropertyGroup>` anyway.

I think the ideal logic here would be to try to find *each* value in an existing `<PropertyGroup>` and if it's not there to add it to the *first* property group.

Failing that, why not just always add it to the first property group and make that a requirement? But don't look for `<TargetFramework>` because that's not right, even for csproj.

**Comment by godefroyo** [comment]
To complete @IanMercer answer, `<PropertyGroup>` element can appear mutiple time for at least 2 reasons : 
- Simple property grouping for developers readability
- Condition based properties, apply property for Debug only for example (see `Condition` attribute (https://docs.microsoft.com/en-us/visualstudio/msbuild/propertygroup-element-msbuild?view=vs-2019)

For replacement logic I would go (like @IanMercer said) with replacing in **all** `PropertyGroup`.
Concerning the `insertArttributes` case, an other option could be to add it in every `PropertyGroup` since MSBuild supports multiple definition and override for a `<Property>`.

Maybe adding a new input for the task :
```json
{
    "name": "InsertAttributes",
    "type": "boolean",
    "label": "Insert attributes",
    "defaultValue": false,
    "required": true,
    "helpMarkDown": "If checked the task will insert missing attributes into the source files specified above."
},
{
    "name": "InsertAttributesMode",
    "type": "pickList",
    "label": "Insert attributes mode",
    "defaultValue": "first",
    "required": false,
    "options": {
        "first": "First PropertyGroup",
        "all": "All PropertyGroup"
    },
    "helpMarkDown": "Specifiy where the missing attributes should be inserted, first PropertyGroup found or all of them."
},
```

**Comment by IanMercer** [comment]
@godefroyo Good point about conditional property groups. But rather than adding yet more options I would prefer: 

* If it's found in *any* property group, replace it in *all* the property groups where it is found (in case it's inside conditional property groups multiple times). 
* If it's not found in *any* property group, add a new property group (to be sure no condition exists on it). 

I certainly would never want it in *all* property group nodes as there are other reasons these end up getting fragmented in a csproj or msbuild props file.

**Comment by godefroyo** [comment]
@IanMercer I agree with your "add in proper node" solution.
So insertAttributes would act as a property level flag : 
First loop would replace only, and a new node would be inserted for nodes not found
```ts
let replace: any = {};
for (const group of result.Project.PropertyGroup) {
    replace = setAssemblyData(group, model, replace);
}

if (model.insertAttributes)
{
    let newGroup = {};
    if (model.packageId && !replace.PackageId) {
            newGroup.PackageId = model.packageId;
            logger.info(`Added PackageId --> ${model.packageId}`);
    }
    ... other properties
    if(Object.keys(newGroup ).length > 0){
        result.Project.PropertyGroup.unshift(newgroup);
    }
}

...
function setAssemblyData(group: any, model: models.NetCore, replace: any, ): void {
...
// Package Id
    if (model.packageId && group.PackageId) {
            group.PackageId = model.packageId;
            replace.packageId = true;
            logger.info(`PackageId --> ${model.packageId}`);
        }
    }
... other properties

return replace;
```

**Comment by BMuuN** [comment]
I've merged the latest changes and added the ability to update `*.prop` files based on your recommendations above however further work is required...

The tasks:
- No longer checks for the `<TargetFramework>` tag.  I agree this was not the correct approach and has been removed.
- Replaces the value of an assembly tag when it's found in _any_ property group.
- If the assembly tag is not found it is added to the first property group.

Based on your recommendations above the task is **not** creating a new property group and adding all "new" assembly tags to this property group.  This is something I will continue to look into but for now it's adding  all "new" assembly tags to the first property group.

This PR was raised some time ago therefore if you require this feature do shout and I'll get it deployed as-is.  If you're not in a rush I will continue to look into creating a new `<PropertyGroup>` for all "new" assembly tags as this is a cleaner approach.

Thanks for your patience, feedback and contribution to this PR and issue #116 it is greatly appreciated 👍

**Comment by BMuuN** [comment]
- Added functionality which creates a `<PropertyGroup>` and all "new" assembly tags are added to this group.
- Added enhancements from PR #172

**Pull request merged**
