### PR TITLE
Fix off by one error (rounding up instead of down)

### PR DESCRIPTION
**Pull request by MatthewSteeples**
When using `1.0.*.*` as the VersionNumber the builds always have tomorrow's date on them. The `ceil` function is round the duration variable up a day, whereas it always wants to round down.

The same change may want making for the number of seconds too, but being off by one there is less noticable

Apologies if I've not updated any unit tests for this, but I'm new to Typescript so I'm not sure how to get anything to run locally

### CODE REVIEW

**Comment by MatthewSteeples** [comment]
If you're able to open up access to the Azure DevOps project for me to review the build logs that would help in fixing this, but in the meantime I'll do some Googling

**Comment by BMuuN** [comment]
Cheers for the PR @MatthewSteeples. Leave this with me and I'll take a look at it a.s.a.p

**Comment by MatthewSteeples** [comment]
Thanks @BMuuN. I haven't been able to get the tests to run locally (probably dependency issues with either NPM or TypeScript)

**Comment by BMuuN** [comment]
@MatthewSteeples the tests are broken in the `master` branch mate. They're working in the `3.0.x` branch which is where the latest development is taking place. In hindsight I should have locked the `master` branch.

**Comment by Jonas-Degn** [comment]
@BMuuN any chance this bugfix comes out anytime soon?

A fix was also suggested back in #134 by using ceil and then subtracting 1, but the bugfix did not include the subtraction of 1 and is therefore 1 day ahead, but I guess using floor is a bit cleaner.

Of course I can also just modify our applications to add a day, just want to know if this is right around the corner before I start modifying applications :)

**Pull request merged**
