### PR TITLE
Node version updated

### PR DESCRIPTION
**Pull request by IgorMikhalev**
Node Version updated according to https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#q-how-can-i-upgrade-my-custom-task-to-the-latest-node

### CODE REVIEW

**Comment by bothzoli** [comment]
Hi @IgorMikhalev,
while you're there, could you please also do the same for the .NET Framework task?
https://github.com/BMuuN/vsts-assemblyinfo-task/blob/master/src/netframework/task.json

**Comment by IgorMikhalev** [comment]
Hi @bothzoli, could you please help me with the pipeline? I do not have access to Azure DevOps, this error message does not look like a problem with the new versions of Node.

**Comment by BMuuN** [comment]
Thanks for the PR @IgorMikhalev and for the contributions @bothzoli 

Some work will be done over the coming weeks to migrate the pipeline from Azure DevOps into GitHub Actions.

**Comment by bothzoli** [comment]
Too easy @BMuuN feel free to tag me if you need any help with the pipeline migration ;)

**Pull request merged**
